name: Deploy Laravel
on:
  push:
    branches: [ "main" ]
jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      -   name: Checkout Repository
          uses: actions/checkout@master
      - name: FTP Deployer
        uses: sand4rt/ftp-deployer@v1.7
        with:
          sftp: false
          host: ${{ secrets.FTP_SERVER }}
          port: 21
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          include: '[".env"]'
